######################################################################
# Automatically generated by qmake (3.0) ?? 8? 28 21:00:47 2017
######################################################################
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt
TARGET = MySudokuGame
INCLUDEPATH += .

# Input
HEADERS += MySudokuGenerater.h  \
    MySudokuSolver.h

SOURCES+=MySudokuGenerater.cpp \
    test.cpp \
    MySudokuSolver.cpp
